### ISSUE TITLE
Incorrect yards_gained on plays with laterals

### ISSUE THREAD

**Issue by SerLancel0t** [mrcaseb/nflfastR#115]
For PlayID 4672 and GameID 2019_02_MIN_GB the yards gained is 4. I believe the official play is a Kirk Cousins pass complete to Adam Thielen for 13 yards, lateral to Tramon Williams for 4 yards, lateral to Stefon Diggs for 4 yards. Stefon Diggs fumbles. For a total yards gained of 17.

I only discovered this when I was trying to find total passing yards for Kirk Cousins this game so it could be could be an issue with how laterals and fumbles are recorded but I've only noticed it for this play. I may also be assessing the data wrong as I'm fairly new to using NFLfastR.

thanks!

**Comment by mrcaseb** [comment]
I can't reproduce this as the `play_id` 4672 doesn't exist for `game_id = "2019_02_MIN_GB"`. The last valid `play_id` is 4380...

    dplyr::filter(nflfastR::fast_scraper("2019_02_MIN_GB"), play_id == 4672)
    #> v Download finished. Adding variables...
    #> v added game variables
    #> v added nflscrapR variables
    #> v added ep variables
    #> v added air_yac_ep variables
    #> v added wp variables
    #> v added air_yac_wp variables
    #> v added cp and cpoe
    #> v added fixed drive variables
    #> v added series variables
    #> v Procedure completed.
    #> # A tibble: 0 x 315
    #> # ... with 315 variables: play_id <dbl>, game_id <chr>, old_game_id <chr>,
    #> #   home_team <chr>, away_team <chr>, season_type <chr>, week <int>, ...

<sup>Created on 2020-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@SerLancel0t please provide a code example to reproduce this issue.

**Comment by guga31bb** [comment]
Correct `play_id` is 4321

**Comment by mrcaseb** [comment]
`yards_gained` is getting a new value for three times in this play:

1. `statID` 15 sets it to 17,

1. `statID` 21 sets it to 13 and finally

1. `statID` 23 sets it to 4.

In fact the play ends in a turnover. This appears to be a strange edge case in desperation plays.

Generally `yards_gained` is getting overwritten for `statID`s 10-13, 15-16, 20-24

![grafik](https://user-images.githubusercontent.com/38586519/94929395-54a37900-04c5-11eb-9815-07f463e9cb5f.png)

**Comment by mrcaseb** [comment]
Since this came up again I thought about it a little more. 
The current principle is that `yards_gained` gets overwritten for

- `stat_ids` 10/11 which are "normal" rushing yards,
- `stat_ids` 12/13 which are yards gained on a rushing play where the player received a lateral,
- `stat_ids` 15/16 which are passing yards,
- `stat_ids` 21/22 which are "normal" receiving yards and 
- `stat_ids` 23/24 which are yards gained on a pass play where the player received a lateral.

In most cases the yards of 15/16 equal the yards of 21/22. The problem are the lateral receiving yards in 23/24. If they are present, the yards of 21/22 don't euqal the yards of 15/16 because **15/16 is the sum of 21-24**

We have multiple choices to handle this in my opinion:

1. Modify `yards_gained` to be the sum of 21-24 (if 23/24 are present). I just tested this and it works. However, in this case `yards_gained` will host the correct passing yards for the `passer_player_name` but incorrect receiving yards for the `receiver_player_name`. This is currently the case but the other way round.

1. Keep `yards_gained` as is (for backwards compatibility) and add new variables 
`rushing_yards` (for stat IDs 10/11) -> yards of `rusher_player_name`,
`lateral_rushing_yards` (for stat IDs 12/13) -> yards of `lateral_rusher_player_name`  will be `NA` in most cases, 
`passing_yards` (for stat IDs 15/16) -> yards of `passer_player_name`,
`receiving_yards` (for stat IDs 21/22) -> yards of `receiver_player_name` and
`lateral_receiving_yards` (for stat IDs 23/24) -> yards of `lateral_receiver_player_name`  will be `NA` in most cases. 
To be clear, the variables `lateral_rusher_player_name` and `lateral_receiver_player_name` are in the data already so I think it's pretty clear we should add the respective yards as well instead of overwriting `yards_gained`.
The new variables `rushing_yards`, `passing_yards` and `receiving_yards` will equal `yards_gained` in mostly all plays and will differ only if laterlas happen in a play.

The one thing we can't solve is that `lateral_*_player_name` and `lateral_*_yards` will get overwritten if multiple laterals happen on the same play. But I host data in another repo the will list all those players with the `game_id`, `play_id` and `yards`

The new variables would be perfect for Fantasy stuff so I think it's worth it to add them. And it's actually quite easy to do so.

**Comment by mrcaseb** [comment]
As an example, this is what `passing_yards` will output

```r
library(dplyr, warn.conflicts = FALSE)
library(nflfastR)

fast_scraper_schedules(2020) %>%
  filter(home_team == "HOU" | away_team == "HOU") %>%
  pull(game_id) %>%
  fast_scraper() %>%
  filter(!is.na(down), complete_pass == 1) %>%
  group_by(passer_player_name) %>%
  filter(passer_player_name == "D.Watson") %>%
  summarise(
    yards_gained = sum(yards_gained),
    passing_yards = sum(passing_yards)
  )
#> √ Download finished. Adding variables...
#> √ added game variables
#> √ added nflscrapR variables
#> √ added ep variables
#> √ added air_yac_ep variables
#> √ added wp variables
#> √ added air_yac_wp variables
#> √ added cp and cpoe
#> √ added fixed drive variables
#> √ added series variables
#> √ Procedure completed.
#> # A tibble: 1 x 3
#>   passer_player_name yards_gained passing_yards
#>   <chr>                     <dbl>         <dbl>
#> 1 D.Watson                   4801          4823
```
Created on 2021-02-11 by the reprex package (v1.0.0)

**Comment by mrcaseb** [comment]
Some insight in this

> The one thing we can't solve is that lateral_*_player_name and lateral_*_yards will get overwritten if multiple laterals happen on the same play. But I host data in another repo the will list all those players with the game_id, play_id and yards

Since the 2001 season there were only 55 plays where multiple players recorded stat id 23 or 24 (24 means the play resulted in a TD, e.g. `2018_14_NE_MIA`) and no play where multiple players recorded stat id 12/13. A list of those plays is hosted and frequently updated [here](https://github.com/mrcaseb/nfl-data/tree/master/data/lateral_yards).

In every other case where those stat ids were recorded it was only one player and he will appear with the correct yards in the above described variables.
