### ISSUE TITLE
False tackle reporting

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#124]
Wanted to see if this was an nflfastR bug or an NFL data issue. Noticed two plays this year which were ruled incomplete passes, but also had tackles recorded (they were initially completed but overturned via challenge). There should be no tackles. The plays:

play_id | game_id
-- | --
2199 | 2020_05_NYG_DAL
2871 | 2020_05_PHI_PIT

**Comment by guga31bb** [comment]
This is because plays with overturned challenges contain the stat IDs for both the original and overturned play. The NFL issues corrections to the underlying data later in the week and we don't pull those in until Wednesday nights. This will be fixed if you check again Thursday; if it's not, please re-open
