### ISSUE TITLE
Play incorrectly designated as rush attempt

### ISSUE THREAD

**Issue by RustyCoal** [mrcaseb/nflfastR#165]
Seahawks, 2020 week 10 @ Rams, 13:40 in 4th quarter. Russell Wilson fumbles, rbsdm boxscore shows it as a rush attempt, but it was a passing play, https://youtu.be/6KRAZuq-1uU?t=534

(I don't use nflfastR just browse rbsdm site and noticed this mistake)

**Comment by guga31bb** [comment]
Thanks for the heads up on this.

This is happening because NFL counts aborted snaps as rushing plays in the official stats (i.e., this is a fumble charged to Wilson on a rush attempt) and there's no way for the package to figure out which plays were meant to be passes or rushes. So unfortunately I don't think there's any way to fix this. In the nflfastR package, there's an aborted snap column, which can be used to filter out plays like this, and maybe in the box score site I should think about adding a check box for excluding plays with aborted snaps. But closing this because I don't think there's anything that can be done (@mrcaseb please chime in if you disagree)

**Comment by RustyCoal** [comment]
Gotcha. Perhaps aborted snaps on passing plays is rare enough it doesn't really matter but this is some undeserved negative rushing EPA across the league if not filtered out?

But w/e, cheers, love the rbsdm site because I'm far too lazy to learn R :)
