### ISSUE TITLE
CP and CPOE not calculating for incomplete passes in 2006-2008

### ISSUE THREAD

**Issue by jeffgould231** [mrcaseb/nflfastR#2]
It looks like CP and CPOE are not calculated for incomplete passes from 2006-2008, or at least no for Buffalo quarterbacks
<img width="628" alt="image" src="https://user-images.githubusercontent.com/48036549/80440211-45951b00-88d6-11ea-9b39-c58b2d02ba8e.png">

**Comment by mrcaseb** [comment]
It took you just a few hours to discover we are discounting Buffalo quarterbacks, lol! 
Kidding aside, we'll look into this. Thanks for reporting this!

**Comment by mrcaseb** [comment]
Can confirm all games between 2006 and 2008 with `cp = NA` on incomplete passes.  There is only one game in this era having non-NA values for `cp` on incomplete passes: Game ID `2007101408`
```R
comb <- play_by_play_2006 %>%
  bind_rows(play_by_play_2007) %>%
  bind_rows(play_by_play_2008)

sum <- comb %>%
  filter(incomplete_pass == 1) %>%
  group_by(cp) %>%
  summarise(
    n=n(), 
    game_id = first(game_id), 
    play_id = first(play_id)
  )
```

`sum`
![grafik](https://user-images.githubusercontent.com/38586519/80483383-4a011880-8956-11ea-9f27-722e27defdf3.png)

**Comment by guga31bb** [comment]
Same. Looking into this now. I'm hoping it's a problem with the data I was using and not the code, but we'll see.

**Comment by guga31bb** [comment]
This has been fixed in the package (but we need to re-scrape and upload to nflfastR-data).

The problem was that in the CP and CPOE calculation, we filter out plays with no targeted receiver to get rid of throwaways. But in 2006-2008, the NFL usually didn't fill the targeted receiver field on incomplete passes, so we were only keeping complete passes (as you found).

We fixed this by adding some parsing of the play description field.
