### ISSUE TITLE
Missing data in load_player_stats()

### ISSUE THREAD

**Issue by SCasanova** [mrcaseb/nflfastR#236]
Brief description of the problem
I've noticed that some data is missing from the load_player_stats function such as Travis Kelce's rookie season (see example below)

``` r
require(magrittr)
#> Loading required package: magrittr
nflfastR::load_player_stats() %>%
  dplyr::filter(season == 2013 & player_id == '00-0030506')
#> # A tibble: 0 x 38
#> # … with 38 variables: player_id <chr>, player_name <chr>, recent_team <chr>,
#> #   season <int>, week <int>, completions <int>, attempts <int>,
#> #   passing_yards <dbl>, passing_tds <int>, interceptions <dbl>, sacks <dbl>,
#> #   sack_fumbles_lost <int>, passing_air_yards <dbl>,
#> #   passing_yards_after_catch <dbl>, passing_first_downs <dbl>,
#> #   passing_epa <dbl>, passing_2pt_conversions <int>, dakota <dbl>,
#> #   carries <int>, rushing_yards <dbl>, rushing_tds <int>,
#> #   rushing_fumbles_lost <dbl>, rushing_first_downs <dbl>, rushing_epa <dbl>,
#> #   rushing_2pt_conversions <int>, receptions <int>, targets <int>,
#> #   receiving_yards <dbl>, receiving_tds <int>, receiving_fumbles_lost <dbl>,
#> #   receiving_air_yards <dbl>, receiving_yards_after_catch <dbl>,
#> #   receiving_first_downs <dbl>, receiving_epa <dbl>,
#> #   receiving_2pt_conversions <int>, special_teams_tds <dbl>,
#> #   fantasy_points <dbl>, fantasy_points_ppr <dbl>
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
```

**Comment by guga31bb** [comment]
Looking at his [game log](https://www.pro-football-reference.com/players/K/KelcTr00/gamelog/2013/), he was only on the field for 1 snap the entire season and then went to injured reserve. Since he didn't record any official statistics, that's not why he's showing up here.

I'm not sure if this is a bug or something that we can do anything about but maybe we need to mention in the docs (a player who doesn't record a stat won't show up in this).

**Comment by SCasanova** [comment]
You’re right that’s my mistake. Thought I checked for that too but missed it
