### ISSUE TITLE
Lateral recovery player and Yards variables

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#27]
Wondering if there could be a variable for lateral_yards and lateral_recovery_player.

I'm looking at 2019_15_CHI_GB, play 4357. It looks like there's a variable for lateral_recovery, but not lateral_recovery_player. On this play it should be J. Horsted.

Similarly, I don't see any variable representing yards gained or lost by the receiver of the lateral. I might be missing this, but I don't see any. On this play, it looks like it should be 9 yards.

Also it appears the lateral_recovery variable has some false positives. I see lateral_recovery == 1 on the following plays but there was no lateral:
2019_03_BAL_KC play 2657 and
2019_15_BUF_PIT play 1703

**Comment by TheMathNinja** [comment]
Added note on false positives for lateral_recovery == 1: it looks like this is generally coming from aborted snaps being coded as lateral_recovery. Is this by design? It really doesn’t seem consistent with the way this variable is defined, and obscures the other (legitimate) uses of it, like the case of the Play 4357 above.

**Comment by guga31bb** [comment]
>I'm looking at 2019_15_CHI_GB, play 4357. It looks like there's a variable for lateral_recovery, but not lateral_recovery_player. On this play it should be J. Horsted.

Yep J.Horsted records stat ID 57 on this play (and 9 yards).

>Also it appears the lateral_recovery variable has some false positives. I see lateral_recovery == 1 on the following plays but there was no lateral:
2019_03_BAL_KC play 2657

According to the NFL source, A.Reiter records a stat ID 57 on this play, which is "If a player recovered a fumble by his own team, then lateraled to a teammate, the yardage gained/lost by the teammate would be recorded with this stat."

>2019_15_BUF_PIT play 1703

Same for D.Johnson on this play, who records stat ID 57.

> Wondering if there could be a variable for lateral_yards and lateral_recovery_player.

I'm wondering if there are plays with multiple of these players which would make things hard. Otherwise, adding 2 columns for this would be pretty easy.

**Comment by TheMathNinja** [comment]
game_id 2016_02_ATL_OAK play_id 4324 is a play which involves 3 laterals. It's a bit unclear to me how many yards each player gained as they held the ball based on the description, though.
