### ISSUE TITLE
JAC/JAX issue

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#28]
I'm noticing that for 2015_14_IND_JAC, play 2069, the "side_of_field" variable reads "JAC" and not "JAX". Seems like this could be disturbing some other variables?

On this play, forced_fumble_team and fumble_recovery_1 team is wrong. It shows IND and not JAX as forcers and recoverers. I encounter this same problem on 2014_13_NYG_JAC play 3382 (and many others, I'm sure). Seems like having JAC in the game name could be a problem too? Wondering if this nomenclature is what is causing the problem.

**Comment by guga31bb** [comment]
This is because games involving the Jags from 2011-2015 are messed up on the NFL's end. We had to do some manual fixes [see here](https://github.com/mrcaseb/nflfastR/blob/master/R/helper_scrape_nfl.R#L70) to fix `posteam`, `td_team` and some other stuff that we really need for everything to work right, otherwise EPA didn't work properly.

If someone wants to submit a PR to fix any other variables, happy to take a look, but unless this is causing any more serious problems probably a low priority to fix.

**Comment by guga31bb** [comment]
The team name confusion across columns has been fixed along with https://github.com/mrcaseb/nflfastR/issues/29 . 

There are some things with the older JAX games that we sadly can't do anything about ("It shows IND and not JAX as forcers and recoverers") because all the data coming from NFL is wrong.
